### ISSUE TITLE
Name with space doesn't work?

### ISSUE THREAD

**Issue by TierraAzur** [Lemmmy/osusig#10]
hi
I been using your sig for along time, but for some reason my sig doesn't work anymore. At first all I do was waiting, idk if there was a bug or something, but is been like 3 months.

Maybe the problem is the space I have in my name?
my user name is Tierra Azur
so maybe is the space... i don't really know.
I hope you can fix it :3
and thx!

and click http://puu.sh/qQhM4/a8f55e45e6.png to see when I put my name

(idk if I should post this here)

**Comment by Lemmmy** [comment]
It's an issue with your osu! avatar, not the space in your name.
