### ISSUE TITLE
Live website is down

### ISSUE THREAD

**Issue by Moebytes** [Lemmmy/osusig#12]
The website "http://lemmmy.pw/osusig" is down. I get the following error on Google Chrome: "lemmmy.pw’s server IP address could not be found. ERR_NAME_NOT_RESOLVED" Please try to fix!

**Comment by Lustyn** [comment]
Unfortunately, the original maintainer of this project is no longer around to bring it back up. If there is still demand for its use, any other community member is welcome to run an instance of the site themselves.

**Comment by Moebytes** [comment]
Oh... My condolences for your loss. I am still interested in using this, but I am not too familiar with php. Is there a guide on how I could self-host this?

**Comment by Lustyn** [comment]
Oh, don't worry, they're still alive. Just not around in the sense that they do not have the time to run internet services or be heavily involved in the osu! community anymore. Sorry for the confusion.

It should be as simple as putting the files up on a webserver which supports PHP and giving it an API key. I believe the important line where it loads the config file for the API key is [here](https://github.com/tmpim/osusig/blob/master/sig.php#L5). It just needs the constant `AKEY` defined. Good luck, and thanks if you do get around to hosting an alternative site!

**Comment by Moebytes** [comment]
Thank you so much, I finally got it working. http://45.77.153.42/
Not sure if I really want to buy a domain name, but it's great for personal use.
