### ISSUE TITLE
Interest in helping

### ISSUE THREAD

**Issue by ghost** [Lemmmy/osusig#4]
Hi Lemmy,

I was wondering if you would like extra help with this? I think this is a neat project and want to try contributing.

**Comment by Lemmmy** [comment]
What do you want to help with?

**Comment by ghost** [comment]
With any new features that you might want to add or possibly with abstraction. Is there a to do list somewhere? I'm going to try and get this up and running on my machine tonight

**Comment by Lemmmy** [comment]
Not a public one, no.
